# .github/workflows/docs-build.yml

name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Especifica la versión de Python que prefieras

    - name: Install Dependencies
      run: |
        python -m venv env
        source env/bin/activate
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt

    - name: Delete old folder build
      run: |
        source env/bin/activate
        cd docs
        make clean

    - name: Build HTML Documentation
      run: |
        source env/bin/activate
        cd docs
        make html

    - name: Upload HTML Documentation
      uses: actions/upload-artifact@v4
      with:
        name: html-docs
        path: docs/build/html/
        
    # 7. Commit and push the generated documentation
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add docs/build/html docs/*.rst
        git commit -m "Auto-update documentation"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
